Iter13
zYoma/go-url-shortener pull request #15
Opened 2024-01-11 13:30 UTC by zYoma

2024-01-13 09:39 UTC, bambruysk requested changes
Нужно поправить момент формирования запросов - в остальном очень хорошо

2024-01-13 09:39 UTC, bambruysk commented on internal/storage/mem/mem.go
> +func (s *Storage) BulkSaveURL(ctx context.Context, data *[]models.InsertData) error {
Не надо передавать слайс по указателю без особой необходимости

2024-01-13 09:39 UTC, bambruysk commented on internal/storage/mem/mem.go
> +			s.db[url.ShortURL] = url.OriginalURL
вряд ли эту операцию можно назвать долгоиграющей, за контекстом можно не следить здесь особо

2024-01-13 09:39 UTC, bambruysk commented on internal/storage/postgres/postgres.go
> +	query := fmt.Sprintf("INSERT INTO url (full_url, short_url) VALUES %s;", strings.Join(sqlValues, ", "))
Это опасное место - лушчe не использовать формирование SQL как строки, а использовать именнованные параметры - иначе злоумышеллник может внедрить в передаваемый URL инъекию,

2024-01-13 11:38 UTC, zYoma commented on internal/storage/mem/mem.go
> +func (s *Storage) BulkSaveURL(ctx context.Context, data *[]models.InsertData) error {
Исправил

2024-01-13 11:38 UTC, zYoma commented on internal/storage/mem/mem.go
> +			s.db[url.ShortURL] = url.OriginalURL
Исправил

2024-01-13 11:39 UTC, zYoma commented on internal/storage/postgres/postgres.go
> +	query := fmt.Sprintf("INSERT INTO url (full_url, short_url) VALUES %s;", strings.Join(sqlValues, ", "))
Изменил так, что чтобы это было безопасно

2024-01-14 11:56 UTC, bambruysk approved these changes
Принято

2024-01-14 11:56 UTC, bambruysk commented on internal/storage/postgres/postgres.go
>  	if err != nil {
если используете pgx то лучше использовать для таких операций batch 

 https://blog.andreiavram.ro/postgresql-batch-operations-golang/

2024-01-14 15:35 UTC, merged