Iter15
zYoma/go-url-shortener pull request #17
Opened 2024-01-24 18:30 UTC by zYoma

2024-01-25 16:04 UTC, bambruysk requested changes
Нужно доработать удаление  следующим образом
Сейчас у нас запускается удаление, на каждый запрос. 
Асинхронное удаление предполагает что мы накапливаем некоторое количество запросов в буфер ( в качестве его можно использовать канал) и когда буфер наполняется до нужного размера то мы делаем батчом удаление сразу пачки urls

Сброс буферв в БД может также выполняться по таймауту ( накопилиось, записали) и по завершению работы сервиса

2024-01-25 16:04 UTC, bambruysk commented on internal/auth/jwt/jwt.go
> +var ErrCreateUUID = errors.New("error create uuid")
обычно мы не начинаем тест ошибки с error - и так понятно что это ошибка

2024-01-25 16:04 UTC, bambruysk commented on internal/handlers/delete_urls.go
> +	userID, _ := req.Context().Value(UserIDKey).(string)
игноришь успех приведения типа - не хорошо 
вообще лучше содздать фукнцию типа getUserFromRequest() (UseID, error) и делать все в ней

2024-01-25 16:04 UTC, bambruysk commented on internal/handlers/delete_urls.go
> +	}()
Это лучше сделать на уровне бизнес-логики

2024-01-25 16:04 UTC, bambruysk commented on internal/handlers/middleware.go
> +		} else {
лучше заменить else на return

2024-01-25 16:04 UTC, bambruysk commented on internal/storage/mem/mem.go
> +}
Для memry storage легко делается

2024-01-25 19:23 UTC, zYoma commented on internal/auth/jwt/jwt.go
> +var ErrCreateUUID = errors.New("error create uuid")
убрал error

2024-01-25 19:23 UTC, zYoma commented on internal/handlers/delete_urls.go
> +	userID, _ := req.Context().Value(UserIDKey).(string)
вынес в getUserFromRequest

2024-01-25 19:23 UTC, zYoma commented on internal/handlers/delete_urls.go
> +	}()
вынес

2024-01-25 19:24 UTC, zYoma commented on internal/handlers/middleware.go
> +		} else {
исправил

2024-01-29 17:56 UTC, bambruysk approved these changes
Принято.

2024-01-29 17:56 UTC, bambruysk commented on internal/handlers/handlers.go
> +
это уже было где-то) - лучше не повторяться ис пользовать канал или контекст для завершения

2024-01-29 17:56 UTC, bambruysk commented on internal/handlers/handlers.go
> +			wg.Done()
лучше в defer

2024-01-29 17:56 UTC, bambruysk commented on internal/handlers/delete_urls.go
> +	h.delChan <- models.UserListURLForDelete{UserID: userID, URLS: listURL}
тут запрос заблокируется - если канал полный, лучше эту запись обернуть в горутину

2024-01-29 17:56 UTC, bambruysk commented on internal/handlers/handlers.go
> +			h.saveMessages(&messages)
помимо этого хорошо бы добавить кейс с наполнением буфера выше определнного размера иначе под нагрузкой можно неуспевать

2024-01-29 18:36 UTC, merged