Iter20
zYoma/go-url-shortener pull request #22
Opened 2024-04-05 11:13 UTC by zYoma

2024-04-06 07:57 UTC, bambruysk requested changes
Нужно подправить 

Советую поставить и настроить golangci-lint

2024-04-06 07:57 UTC, bambruysk commented on cmd/staticlint/main.go
> +		}
слишком глубокая вложенность - лучше использовать ранний выход
Вместо свитча с одним кейсом - лучше использовать if
Тело цикла можно вынести в отдельную функцию

2024-04-06 09:50 UTC, zYoma commented on cmd/staticlint/main.go
> +		}
Сделал как рекомендовано. Добавил  golangci-lint

2024-04-11 21:07 UTC, bambruysk approved these changes
Принято

2024-04-12 04:16 UTC, merged