Iter5
zYoma/go-url-shortener pull request #6
Opened 2023-12-02 13:05 UTC by zYoma

2023-12-03 08:43 UTC, bambruysk requested changes
Очень круто сделано. Добавил несколько замечаний по структуре стоит подправить время еще есть

2023-12-03 08:43 UTC, bambruysk commented on internal/app/app.go
> +	server := server.New(address, r)
Вот это все можно перенести в handlers - по сути слой API - 
А здесь только создавать этот слой через конструктор -  разделение отвественности. Тогда приложение не отвечает за то, какие маршруты обрабатываются и нужно ли добавлять новый хендлер ддя нового маршрута

2023-12-03 08:43 UTC, bambruysk commented on internal/app/app.go
> +	})
Для небольших приложений использование замыканий довольно удобно, однако при увеличении количества роутов придется столкнутся с неприятной запутанностью происходящего

Так же обрати внимание что provider и base shortURL - статичны и не изменяются. 

Поэтому на старте мы можем создать структуру с provider, config  и другими нужным штуками и сделать ее методами хендлеры подходящими под ServeHTTP, а все остальное будет использоваться  из структуры 

Не самый очевидный момент но сигнатура функции не зависит от типа приемника и в r.Post может передаваться как свободная функция, так и метод какой-то структуры

2023-12-03 08:43 UTC, bambruysk commented on internal/config/config.go
> +func ParseFlags() (string, string) {
Количество конфигурационных переменных обычно ( и у нас тоже) растет чуть ли не по экспоненте
Поэтому удобно было бы создать структуру содержащую все конфиги приложения и возвращать ее

2023-12-03 08:43 UTC, bambruysk commented on internal/app/server/app.go
> +		panic(err)
паниковать вне функции main не очень хорошо, Лучше возвращать ошибку, Функции типа Must обычно делаются для тех случаев, которые легко выявляются на старте приложения ( например, парсинг какого-то шаблона и тп)  где приложение сразу падает если шаблон неправильный
Здесь сервер возвращает ошибку при закрытии приложения и можно словить панику на выходе

в общем простое правило - паникуем только в main

2023-12-03 08:43 UTC, bambruysk commented on internal/handlers/handlers.go
> +		w.Write([]byte(err.Error()))
Здесь стоит записать в ответ статус

есть неплохая функция https://pkg.go.dev/net/http#Error которой удобно пользоваться для этого

2023-12-03 08:43 UTC, bambruysk commented on internal/handlers/handlers_test.go
> +	testCases := []struct {
обычно в тесткейсах указываем еще имя теста  и его передаем функции Run

2023-12-03 08:43 UTC, bambruysk commented on internal/handlers/handlers_test.go
> +	provider := mem.New()
Не очень хорошо, что тесты зависят от реализвации внешнего пакета 

Здесь хорошо подошло бы мокание интерфейса, но об этом мы будем говорить позже

2023-12-03 08:43 UTC, bambruysk commented on internal/storage/mem/mem.go
> +	db map[string]string
Здесь работа идет с мапой из разных потоков, лучше защитить ее мьютексом 
Это опять же поясняется в следующих главах и исправления не требует срочного, однако так как чувствуется что ты силен в программировании то лучше учесть сейчас, так как это является очень грубой ошибкой в реальных проектах

2023-12-03 08:43 UTC, bambruysk commented on cmd/shortener/main.go
> +	go application.Server.MustRun()
логично было бы здесь вызывать appliction.Run() - и в ней вызывать вот это все и  остальное

2023-12-03 16:00 UTC, zYoma commented on internal/app/app.go
> +	server := server.New(address, r)
Вынес в handlers

2023-12-03 16:01 UTC, zYoma commented on internal/app/app.go
> +	})
Надеюсь правильно понял идею. Добавил структуру HandlerService (в нейминге не уверен), сделал ее методами функции обработчики. Удалось уйти от замыканий.

2023-12-03 16:01 UTC, zYoma commented on internal/config/config.go
> +func ParseFlags() (string, string) {
Вынес настройки в отдельную стркутуру

2023-12-03 16:02 UTC, zYoma commented on internal/app/server/app.go
> +		panic(err)
Избавился от MustRun.  вынес панику в main

2023-12-03 16:03 UTC, zYoma commented on internal/handlers/handlers.go
> +		w.Write([]byte(err.Error()))
Спасибо, использовал данный метод

2023-12-03 16:03 UTC, zYoma commented on internal/handlers/handlers_test.go
> +	testCases := []struct {
Добавил name всем кейсам

2023-12-03 16:04 UTC, zYoma commented on internal/handlers/handlers_test.go
> +	provider := mem.New()
Вот тут сложно, пытался реализовать как я бы сделал в pytest - создать фейковый storage и сохранить в него то что нужно для теста, но не успешно, оставлю так до темы с моками на курсе

2023-12-03 16:05 UTC, zYoma commented on internal/storage/mem/mem.go
> +	db map[string]string
Добавил Mutex, надеюсь правильно

2023-12-03 16:06 UTC, zYoma commented on cmd/shortener/main.go
> +	go application.Server.MustRun()
добавил метод Run структуре, перенес туда запуск

2023-12-04 17:57 UTC, zYoma commented on internal/storage/mem/mem.go
> +	db map[string]string
Интересно, а как правильно работать с мьютексом когда у нас несколько подов в кубере с нашим приложением? В python я использую распределенную блокировку, например в redis, чтобы гарантировать эксклюзивный доступ. А как правильно это сделать в go?

2023-12-05 17:58 UTC, bambruysk approved these changes
Очень хорошо

Структуру как правильно реализовать  архитектуру на уровне приложения мы рассмотрим дальше

2023-12-05 18:05 UTC, bambruysk commented on internal/app/app.go
> +func New(address string, baseShortURL string) *App {
Ей бы все таки конфиг принимать

я бы этот кусок переделал так

unc New(address string, baseShortURL string) *App {
Comment
Ей бы все таки конфиг принимать

я бы этот кусок переделал так

func New(cfg * config.Config) *App {

 
	// создаем провайдер для storage
	provider := mem.New() // здесь все про хранение
 
	// создаем сервер
	server := server.New(provider, cfg) // здесь все про http

	return &App{Server: server}

}

2023-12-05 18:08 UTC, bambruysk approved these changes

2023-12-05 18:08 UTC, bambruysk commented on internal/app/server/app.go
> +}
Лучше бы эту структуру назвать Server или HTTPServer -  а то путаница с приложением в пакете app

2023-12-06 06:48 UTC, zYoma commented on internal/app/app.go
> +func New(address string, baseShortURL string) *App {
исправил

2023-12-06 06:48 UTC, zYoma commented on internal/app/server/app.go
> +}
исправил

2023-12-06 06:49 UTC, merged